{
 "title": "Github Traffic",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Stars",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(github_traffic_stars) by (repository)",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  { "title": "Views", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Views",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(github_traffic_views[1h])",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Views (unique)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(github_traffic_unique_views[1h])",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  { "title": "Clones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Clones",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(github_traffic_clones[1h])",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Clones (unique)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(github_traffic_unique_clones[1h])",
     "legendFormat": "{{repository}}"
    }
   ]
  }
 ]
}