---
name: "push"

on:
  release:
    types:
      - published

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: "Setup buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login into ghcr"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build image"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ghcr.io/khulnasoft/github-insights:latest,ghcr.io/khulnasoft/github-insights:${{ github.event.release.tag_name }}
